FROM ubuntu:14.04

ARG HTTP_PROXY=${HTTP_PROXY}
ARG HTTPS_PROXY=${HTTPS_PROXY}

ENV http_proxy $HTTP_PROXY
ENV https_proxy $HTTPS_PROXY
ENV CONSUL_IP $CONSUL_IP
ENV CONSUL_VERSION 1.0.6

RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get install -y realpath && \
    apt-get install -y unzip && \
    apt-get install -y git && \
    apt-get install -y curl && \
    apt-get install -y wget

RUN wget -qO /tmp/consul.zip "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip" && \
    unzip -d /bin /tmp/consul.zip && \
    chmod 755 /bin/consul && \
    rm /tmp/consul.zip

EXPOSE 8200
EXPOSE 8080

RUN mkdir /dkv_mount_path && \
    mkdir /dkv_mount_path/consul_data && \
    mkdir /dkv_mount_path/configs && \
    mkdir /dkv_mount_path/configs/default

WORKDIR /dkv_mount_path
ADD ./dkv /dkv_mount_path/
ADD ./docker-entrypoint.sh /dkv_mount_path/

ENTRYPOINT /dkv_mount_path/docker-entrypoint.sh
#ENTRYPOINT /bin/bash